Import("env")

gmock = SConscript(
    "gmock/SConscript",
    exports="env"
)

jemalloc = SConscript(
    "jemalloc/SConscript",
    exports="env"
)

contrib = {
    "gmock" : gmock,
    "jemalloc" : jemalloc
}

Return("contrib")
