Import("env")

jemalloc_lib = env.StaticLibrary(
    "jemalloc",
    [
        "src/jemalloc.c",
        "src/arena.c",
        "src/atomic.c",
        "src/base.c",
        "src/bitmap.c",
        "src/chunk.c",
        "src/chunk_dss.c",
        "src/chunk_mmap.c",
        "src/ckh.c",
        "src/ctl.c",
        "src/extent.c",
        "src/hash.c",
        "src/huge.c",
        "src/mb.c",
        "src/mutex.c",
        "src/pages.c",
        "src/prof.c",
        "src/quarantine.c",
        "src/rtree.c",
        "src/stats.c",
        "src/tcache.c",
        "src/util.c",
        "src/tsd.c",
        "src/zone.c"
    ],
    CFLAGS = [
        "-std=gnu99",
        "-Wall",
        "-Werror=declaration-after-statement",
        "-pipe",
        "-g3",
        "-O3",
        "-funroll-loops",
        "-D_REENTRANT",
    ],
    CPATH = [
        ".",
        "include"
    ]
)

path = Dir(".").srcnode().abspath

jemalloc = {
    "LIBS" : jemalloc_lib,
    "INCLUDE" : path + "/include"
}

Return("jemalloc")
